In [5]:
from sklearn.svm import SVC
from sklearn import svm
import numpy as np

In [6]:
X=np.array([[3,4],[1,4],[2,3],[6,-1],[7,-1],[5,-3]])
y=np.array([-1,-1,-1,1,1,1])

In [7]:
l=SVC(C=1e5,kernel="linear")
l.fit(X,y)

SVC(C=100000.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [8]:
print("w=",l.coef_)
print("b=",l.intercept_)
print("Indices of support vectors=",l.support_)
print("Support vectors=",l.support_vectors_)
print("No. of support vectors from each class=",l.n_support_)
print("coefficient of support vectors in decision function=",np.abs(l.dual_coef_))

w= [[ 0.25 -0.25]]
b= [-0.75]
Indices of support vectors= [2 3]
Support vectors= [[ 2.  3.]
 [ 6. -1.]]
No. of support vectors from each class= [1 1]
coefficient of support vectors in decision function= [[0.0625 0.0625]]


In [10]:
import pandas as pd
data=pd.read_csv("/home/ignis/B2_heart.csv")
data.head()
x=data.drop("target",axis=1)
y=data.target

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [12]:
linear=svm.SVC(kernel="linear")
linear.fit(x_train,y_train)

print(linear.support_vectors_)

[[61.  1.  3. ...  1.  2.  2.]
 [46.  1.  0. ...  2.  0.  3.]
 [65.  1.  3. ...  1.  1.  2.]
 ...
 [64.  0.  0. ...  2.  0.  2.]
 [58.  1.  2. ...  1.  0.  3.]
 [58.  1.  1. ...  1.  4.  3.]]


In [13]:
print(linear.n_support_)
y_pred=linear.predict(x_test)

[45 48]


In [14]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.8901098901098901


In [15]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[39  9]
 [ 1 42]]


In [16]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.97      0.81      0.89        48
           1       0.82      0.98      0.89        43

    accuracy                           0.89        91
   macro avg       0.90      0.89      0.89        91
weighted avg       0.90      0.89      0.89        91



In [17]:
model1=SVC(kernel="sigmoid")
model2=SVC(kernel="poly")
model3=SVC(kernel="rbf")

In [18]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [19]:
y_pred1=model1.predict(x_test)
y_pred2=model2.predict(x_test)
y_pred3=model3.predict(x_test)

In [20]:
print("prediction by model1",accuracy_score(y_test,y_pred1))
print("prediction by model2",accuracy_score(y_test,y_pred2))
print("prediction by model3",accuracy_score(y_test,y_pred1))

prediction by model1 0.4725274725274725
prediction by model2 0.6703296703296703
prediction by model3 0.4725274725274725
